[package]
name = "anodrel-windows-uia"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-ui = { path = "../../crates/ui" }
anodrel-ui-session = { path = "../../crates/ui-session" }
anodrel-windows-accessibility = { path = "../windows-accessibility" }

[dev-dependencies]
anodrel-ui-document = { path = "../../crates/ui-document" }
