[package]
name = "anodrel-linux-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-client = { path = "../../crates/client" }
anodrel-json = { path = "../../crates/json" }
anodrel-protocol = { path = "../../crates/protocol" }
anodrel-transport = { path = "../../crates/transport" }
