[package]
name = "anodrel-native-app-tool"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "anodrel-native-app-tool"
path = "src/main.rs"

[dev-dependencies]
anodrel-core = { path = "../../crates/core" }
anodrel-menu = { path = "../../crates/menu" }
anodrel-notifications = { path = "../../crates/notifications" }
anodrel-protocol = { path = "../../crates/protocol" }
anodrel-ui = { path = "../../crates/ui" }
anodrel-ui-document = { path = "../../crates/ui-document" }
anodrel-ui-session = { path = "../../crates/ui-session" }
anodrel-window = { path = "../../crates/window" }
anodrel-windows-bootstrap = { path = "../../adapters/windows-bootstrap" }
anodrel-windows-pipe = { path = "../../adapters/windows-pipe" }
