//! Fixed source and documentation templates for one generated project.

use std::path::{Path, PathBuf};

mod context_menu;
mod form;
mod live_status;
mod menu;
mod multi_window;
mod notification;
mod scroll_window;
mod tray;
mod window_controls;

pub struct TemplateContext {
    pub project_slug: String,
    pub windows_ui_sdk_path: PathBuf,
    pub host_manifest_path: PathBuf,
}

pub fn cargo_toml(context: &TemplateContext) -> String {
    format!(
        "[package]\nname = {project_slug}\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\nlicense = \"MIT OR Apache-2.0\"\n\n[dependencies]\nanodrel-windows-ui-sdk = {{ path = {windows_ui_sdk_path} }}\n",
        project_slug = quoted(&context.project_slug),
        windows_ui_sdk_path = quoted_path(&context.windows_ui_sdk_path),
    )
}

pub fn main_source(display_label: &str) -> String {
    let document = document_json(display_label);
    format!("{MAIN_PREFIX}{}{MAIN_SUFFIX}", quoted(&document))
}

pub fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel template\n\nThis is a small Windows native UI project generated by `anodrel-native-app-tool`. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed Anodrel document, waits for its one semantic button action, and then requests that its own host-created session closes. It contains no raw protocol envelopes, host policy, capability declaration, OS window handle, package identity, configuration loader, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n```powershell\ncargo build --release\n```\n\nThis produces `target\\release\\{project_slug}.exe`. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit development-template host route:\n\n```powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-template-client $clientPath\n```\n\nThe host opens an **Anodrel Native Template** window. Activate **Complete template session** to let this executable close only its own session. The host grants exactly document replacement, semantic-action reading, and self-close; it ignores any project-supplied capability, identity, title, or window setting.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

pub fn menu_main_source(display_label: &str) -> String {
    menu::main_source(display_label)
}

pub fn context_menu_main_source(display_label: &str) -> String {
    context_menu::main_source(display_label)
}

pub fn form_main_source(display_label: &str) -> String {
    form::main_source(display_label)
}

pub fn form_readme(context: &TemplateContext) -> String {
    form::readme(context)
}

pub fn live_status_main_source(display_label: &str) -> String {
    live_status::main_source(display_label)
}

pub fn live_status_readme(context: &TemplateContext) -> String {
    live_status::readme(context)
}

pub fn menu_readme(context: &TemplateContext) -> String {
    menu::readme(context)
}

pub fn context_menu_readme(context: &TemplateContext) -> String {
    context_menu::readme(context)
}

pub fn tray_main_source(display_label: &str) -> String {
    tray::main_source(display_label)
}

pub fn tray_readme(context: &TemplateContext) -> String {
    tray::readme(context)
}

pub fn notification_main_source(display_label: &str) -> String {
    notification::main_source(display_label)
}

pub fn notification_readme(context: &TemplateContext) -> String {
    notification::readme(context)
}

pub fn multi_window_main_source(display_label: &str) -> String {
    multi_window::main_source(display_label)
}

pub fn multi_window_readme(context: &TemplateContext) -> String {
    multi_window::readme(context)
}

pub fn scroll_window_main_source(display_label: &str) -> String {
    scroll_window::main_source(display_label)
}

pub fn scroll_window_readme(context: &TemplateContext) -> String {
    scroll_window::readme(context)
}

pub fn window_controls_main_source(display_label: &str) -> String {
    window_controls::main_source(display_label)
}

pub fn window_controls_readme(context: &TemplateContext) -> String {
    window_controls::readme(context)
}

pub(super) fn document_json(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.detail\",\"kind\":\"text\",\"value\":\"This host-owned window uses direct Windows APIs and Anodrel's typed native UI client.\",\"fontSize\":16,\"tone\":\"secondary\"}},{{\"id\":\"template.complete\",\"kind\":\"action\",\"label\":\"Complete template session\",\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}"
    )
}

pub(super) fn quoted(value: &str) -> String {
    format!("\"{}\"", rust_string(value))
}

fn quoted_path(path: &Path) -> String {
    quoted(&cargo_path(path))
}

fn cargo_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub(super) fn windows_path(path: &Path) -> String {
    path.to_string_lossy().replace('/', "\\")
}

pub(super) fn json_string(value: &str) -> String {
    let mut escaped = String::from("\"");
    for character in value.chars() {
        match character {
            '\"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\u{08}' => escaped.push_str("\\b"),
            '\u{0C}' => escaped.push_str("\\f"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character if character.is_control() => {
                use std::fmt::Write as _;
                let _ = write!(escaped, "\\u{:04x}", character as u32);
            }
            character => escaped.push(character),
        }
    }
    escaped.push('\"');
    escaped
}

fn rust_string(value: &str) -> String {
    value.escape_default().to_string()
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel UI template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the typed three-operation
//! UI client, and never selects host capabilities or native window resources.

use std::{process::ExitCode, thread};

use anodrel_windows_ui_sdk::{
    InteractivePollSchedule, WindowsUiConnectionError, WindowsUiSession,
};

const COMPLETE_ACTION: &str = "template.complete";
const DOCUMENT: &str = "##;

const MAIN_SUFFIX: &str = r##";


#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    EventReadFailed,
    ActionNotObserved,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 51,
            Self::EndpointUnavailable => 52,
            Self::AuthenticationRejected => 53,
            Self::DocumentRejected => 54,
            Self::EventReadFailed => 55,
            Self::ActionNotObserved => 56,
            Self::CloseRejected => 57,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };
    let Ok(revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    for interval in InteractivePollSchedule::new() {
        let Ok(batch) = session.read_actions() else {
            return Stage::EventReadFailed;
        };
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Stage::EventReadFailed;
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            actions
                if actions.iter().all(|action| {
                    action.action() == COMPLETE_ACTION && action.revision().value() == 1
                }) => {
                    return if session.close().is_ok() {
                        Stage::Completed
                    } else {
                        Stage::CloseRejected
                    };
                }
            _ => return Stage::EventReadFailed,
        }
    }
    Stage::ActionNotObserved
}
"##;

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{
        TemplateContext, cargo_toml, context_menu_main_source, document_json, form_main_source,
        live_status_main_source, main_source, menu_main_source, multi_window_main_source,
        scroll_window_main_source, tray_main_source, window_controls_main_source,
    };

    #[test]
    fn generated_manifest_uses_only_the_relative_windows_sdk() {
        let context = TemplateContext {
            project_slug: "native-example".to_owned(),
            windows_ui_sdk_path: Path::new("../../native/adapters/windows-ui-sdk").to_path_buf(),
            host_manifest_path: Path::new("../../native/Cargo.toml").to_path_buf(),
        };
        let manifest = cargo_toml(&context);
        assert!(manifest.contains("anodrel-windows-ui-sdk"));
        assert!(manifest.contains("path = \"../../native/adapters/windows-ui-sdk\""));
        assert!(!manifest.contains("anodrel-client"));
        assert!(!manifest.contains("anodrel-ui-client"));
        assert!(!manifest.contains("anodrel-windows-client"));
        assert!(!manifest.contains(":/"));
    }

    #[test]
    fn generated_source_escapes_quotes_backslashes_and_raw_literal_endings() {
        let label = "Quote \" then slash \\ then \"#";
        let source = main_source(label);
        let document = document_json(label);
        let decoded = anodrel_ui_document::decode(&document)
            .expect("escaped generated document remains a strict v1 document");
        assert!(source.contains("const DOCUMENT: &str = \""));
        assert!(source.contains("template.complete"));
        assert!(!source.contains("const DOCUMENT: &str = r#"));
        assert_eq!(decoded.root().id().as_str(), "template.root");
    }

    #[test]
    fn menu_source_is_closed_over_one_fixed_model_and_action() {
        let source = menu_main_source("Menu \"Template\" \\ App");
        assert!(source.contains("replace_menu_v1"));
        assert!(source.contains("read_events"));
        assert!(source.contains("template.menu.complete"));
        assert!(!source.contains("template.complete\""));
    }

    #[test]
    fn context_menu_source_uses_the_distinct_typed_popup_surface() {
        let source = context_menu_main_source("Context \"Menu\" Template");
        assert!(source.contains("replace_context_menu_v1"));
        assert!(source.contains("read_context_menu_actions"));
        assert!(source.contains("template.context.complete"));
        assert!(!source.contains("replace_menu_v1"));
    }

    #[test]
    fn tray_source_uses_the_distinct_typed_notification_area_surface() {
        let source = tray_main_source("Tray \"Template\"");
        assert!(source.contains("replace_tray_v1"));
        assert!(source.contains("read_tray_actions"));
        assert!(source.contains("template.tray.complete"));
        assert!(!source.contains("replace_context_menu_v1"));
        assert!(!source.contains("replace_menu_v1"));
    }

    #[test]
    fn form_source_is_closed_over_one_fixed_submit_time_snapshot() {
        let source = form_main_source("Form \"Template\" \\ App");
        assert!(source.contains("read_fields"));
        assert!(source.contains("template.form.name"));
        assert!(source.contains("template.form.submit"));
        assert_eq!(source.matches("replace_document_v1(").count(), 1);
    }

    #[test]
    fn live_status_source_uses_one_visible_status_per_version_three_document() {
        let source = live_status_main_source("Live \"Status\" Template");
        assert_eq!(source.matches("replace_document_v3(").count(), 3);
        for action in [
            "template.status.polite",
            "template.status.assertive",
            "template.status.complete",
        ] {
            assert!(
                source.contains(action),
                "generated source includes {action}"
            );
        }
        assert!(!source.contains("replace_document_v1("));
    }

    #[test]
    fn multi_window_source_is_closed_over_its_fixed_walkthrough() {
        let source = multi_window_main_source("Multi \"Window\" Template");
        for method in [
            "open_window_v1",
            "replace_window_document_v1",
            "read_window_actions",
            "close_window",
        ] {
            assert!(source.contains(method), "generated source uses {method}");
        }
        for action in [
            "template.window.open",
            "template.window.update",
            "template.window.complete",
        ] {
            assert!(
                source.contains(action),
                "generated source includes {action}"
            );
        }
        assert!(!source.contains("--native-template-client"));
    }

    #[test]
    fn scroll_window_source_uses_only_the_explicit_version_two_secondary_route() {
        let source = scroll_window_main_source("Scroll \"Window\" Template");
        for method in [
            "open_window_v2",
            "replace_window_document_v2",
            "read_window_actions",
            "close_window",
        ] {
            assert!(source.contains(method), "generated source uses {method}");
        }
        for action in [
            "template.scroll.open",
            "template.scroll.reveal",
            "template.scroll.complete",
        ] {
            assert!(
                source.contains(action),
                "generated source includes {action}"
            );
        }
        assert!(!source.contains("open_window_v1"));
        assert!(!source.contains("replace_window_document_v1"));
        assert!(!source.contains("replace_document_v3"));
        assert!(!source.contains("protocolVersion"));
        assert!(!source.contains("--native-"));
        assert!(!source.contains("scrollOffset"));
    }

    #[test]
    fn window_controls_source_uses_all_five_typed_targetless_controls() {
        let source = window_controls_main_source("Window \"Controls\" Template");
        for method in [
            "set_window_title",
            "set_window_state",
            "request_window_focus",
            "set_window_fullscreen",
            "set_window_size",
        ] {
            assert!(source.contains(method), "generated source uses {method}");
        }
        for action in [
            "template.controls.title",
            "template.controls.resize",
            "template.controls.maximize",
            "template.controls.restore",
            "template.controls.focus",
            "template.controls.fullscreen",
            "template.controls.windowed",
            "template.controls.complete",
        ] {
            assert!(
                source.contains(action),
                "generated source includes {action}"
            );
        }
        assert!(!source.contains("protocolVersion"));
        assert!(!source.contains("request("));
        assert!(!source.contains("native-window-controls-template-client"));
    }
}
