[package]
name = "anodrel-native-window-controls-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "anodrel-native-window-controls-client"
path = "src/main.rs"

[dependencies]
anodrel-windows-ui-sdk = { path = "../../adapters/windows-ui-sdk" }

[dev-dependencies]
anodrel-ui-document = { path = "../../crates/ui-document" }
