[package]
name = "anodrel-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-clipboard = { path = "../clipboard" }
anodrel-core = { path = "../core" }
anodrel-external-links = { path = "../external-links" }
anodrel-file-dialog = { path = "../file-dialog" }
anodrel-protocol = { path = "../protocol" }
anodrel-ui-session = { path = "../ui-session" }
anodrel-wire = { path = "../wire" }

[dev-dependencies]
anodrel-ui = { path = "../ui" }
