[package]
name = "anodrel-windows-updater"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-windows-update-cache = { path = "../windows-update-cache" }
anodrel-windows-update-download = { path = "../windows-update-download" }
anodrel-windows-update-handoff = { path = "../windows-update-handoff" }
anodrel-windows-installer = { path = "../../tools/windows-installer" }

[dev-dependencies]
anodrel-windows-policy = { path = "../windows-policy" }
