//! Fixed source and documentation for the retained native file-write template.

use super::{TemplateContext, json_string, quoted, windows_path};

const OUTPUT_TEXT: &str = "Hello from Anodrel's retained native file-write template.\n";

pub(super) fn main_source(display_label: &str) -> String {
    let document = document_json(display_label);
    format!(
        "{MAIN_PREFIX}{}{MAIN_DOCUMENT_TO_TEXT}{}{MAIN_SUFFIX}",
        quoted(&document),
        quoted(OUTPUT_TEXT),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel file-write template\n\nThis small Windows-native project is generated by `anodrel-native-app-tool`. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed document, opens one host-owned save dialog with a compiled-in **Text documents** / `txt` filter, writes one fixed short UTF-8 line only through the selected retained object, and closes its own session. It has no raw protocol envelope, path input, filename input, general filesystem API, handle, readback, append mode, offset, stream, progress result, atomicity option, network access, package identity, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n```powershell\ncargo build --release\n```\n\nThis produces `target\\release\\{project_slug}.exe`. It is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit retained-output development route:\n\n```powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-file-write-template-client $clientPath\n```\n\nThe host opens an **Anodrel Native File Write Template** window and then the save dialog. Choose a fresh `.txt` destination. The generated project writes this exact line and then closes:\n\n```text\n{OUTPUT_TEXT}```\n\nRun it again and cancel the dialog to confirm that cancellation closes cleanly and creates no new output. The host grants exactly document replacement, save-file selection, retained text writing, and self-close. The selected path is display-only; only the opaque one-use reference remains usable for the one write. The operation is not an atomic replacement guarantee.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document_json(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.file-write.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.file-write.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE FILE-WRITE TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.file-write.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.file-write.detail\",\"kind\":\"text\",\"value\":\"Choose a .txt output to write the fixed template line, or cancel to test cleanup.\",\"fontSize\":16,\"tone\":\"secondary\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel retained file-write template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe and writes only through one
//! opaque output reference returned from the host-owned save picker.

use std::process::ExitCode;

use anodrel_windows_ui_sdk::{
    FileDialogFilter, SaveSelectionResult, WindowsUiConnectionError, WindowsUiSession,
};

const DOCUMENT: &str = "##;

const MAIN_DOCUMENT_TO_TEXT: &str = r##";
const OUTPUT_TEXT: &str = "##;

const MAIN_SUFFIX: &str = r##";

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    FilterRejected,
    SelectionRejected,
    WriteRejected,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 101,
            Self::EndpointUnavailable => 102,
            Self::AuthenticationRejected => 103,
            Self::DocumentRejected => 104,
            Self::FilterRejected => 105,
            Self::SelectionRejected => 106,
            Self::WriteRejected => 107,
            Self::CloseRejected => 108,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };
    let Ok(document_revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if document_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    let Ok(filter) = FileDialogFilter::new("Text documents", vec!["txt".to_owned()]) else {
        return Stage::FilterRejected;
    };
    match session.select_save_file_v2(&[filter]) {
        Ok(SaveSelectionResult::Selected(selection)) => {
            if session
                .write_selected_text(selection.reference(), OUTPUT_TEXT)
                .is_err()
            {
                return Stage::WriteRejected;
            }
        }
        Ok(SaveSelectionResult::Cancelled) => {}
        Err(_) => return Stage::SelectionRejected,
    }
    if session.close().is_ok() {
        Stage::Completed
    } else {
        Stage::CloseRejected
    }
}
"##;

#[cfg(test)]
mod tests {
    use super::{OUTPUT_TEXT, document_json, main_source};

    #[test]
    fn fixed_source_uses_only_one_retained_selected_output() {
        assert!(anodrel_ui_document::decode(&document_json("File Write App")).is_ok());
        let source = main_source("File Write App");
        assert!(source.contains("select_save_file_v2(&[filter])"));
        assert!(source.contains("write_selected_text(selection.reference(), OUTPUT_TEXT)"));
        assert!(source.contains("SaveSelectionResult::Cancelled"));
        assert!(!source.contains("std::fs"));
        assert!(!source.contains("read_actions"));
        assert!(!source.contains("write_selected_binary"));
        assert_eq!(
            OUTPUT_TEXT,
            "Hello from Anodrel's retained native file-write template.\n"
        );
    }
}
