//! Fixed source and documentation for the retained native binary-write template.

use super::{TemplateContext, json_string, quoted, windows_path};

const BINARY_BASE64URL: &str = "QW5vZHJlbAD_";
const BINARY_BYTES: &[u8] = &[0x41, 0x6E, 0x6F, 0x64, 0x72, 0x65, 0x6C, 0x00, 0xFF];

pub(super) fn main_source(display_label: &str) -> String {
    let document = document_json(display_label);
    format!(
        "{MAIN_PREFIX}{}{MAIN_DOCUMENT_TO_DATA}{}{MAIN_DATA_TO_BYTES}{}{MAIN_SUFFIX}",
        quoted(&document),
        quoted(BINARY_BASE64URL),
        bytes_text(),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel binary file-write template\n\nThis small Windows-native project is generated by `anodrel-native-app-tool`. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed document, opens one host-owned save dialog with a compiled-in **Binary files** / `bin` filter, writes one fixed bounded byte sequence only through the selected retained object, and closes its own session. It has no raw protocol envelope, path input, filename input, general filesystem API, handle, MIME type, encoding option, readback, append mode, offset, stream, progress result, atomicity option, network access, package identity, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n```powershell\ncargo build --release\n```\n\nThis produces `target\\release\\{project_slug}.exe`. It is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit retained binary-output development route:\n\n```powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-file-binary-write-template-client $clientPath\n```\n\nThe host opens an **Anodrel Native Binary File Write Template** window, then the save dialog. Choose a fresh `.bin` destination. The generated project writes these exact bytes and closes:\n\n```text\n41 6E 6F 64 72 65 6C 00 FF\n```\n\nRun it again and cancel the dialog to confirm that cancellation closes cleanly and creates no new output. The host grants exactly document replacement, save-file selection, retained binary writing, and self-close. The selected path is display-only; only the opaque one-use reference remains usable for the one write. The operation is not an atomic replacement guarantee.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document_json(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.file-binary-write.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.file-binary-write.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE BINARY FILE-WRITE TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.file-binary-write.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.file-binary-write.detail\",\"kind\":\"text\",\"value\":\"Choose a .bin output to write the fixed template bytes, or cancel to test cleanup.\",\"fontSize\":16,\"tone\":\"secondary\"}}]}}}}"
    )
}

fn bytes_text() -> String {
    BINARY_BYTES
        .iter()
        .map(|byte| format!("0x{byte:02X}"))
        .collect::<Vec<_>>()
        .join(", ")
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel retained binary file-write template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe and writes only through one
//! opaque output reference returned from the host-owned save picker.

use std::process::ExitCode;

use anodrel_windows_ui_sdk::{
    FileBinaryData, FileDialogFilter, SaveSelectionResult, WindowsUiConnectionError,
    WindowsUiSession,
};

const DOCUMENT: &str = "##;

const MAIN_DOCUMENT_TO_DATA: &str = r##";
const BINARY_BASE64URL: &str = "##;

const MAIN_DATA_TO_BYTES: &str = r##";
const BINARY_BYTES: &[u8] = &["##;

const MAIN_SUFFIX: &str = r##"];

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    FilterRejected,
    BinaryDataRejected,
    SelectionRejected,
    WriteRejected,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 111,
            Self::EndpointUnavailable => 112,
            Self::AuthenticationRejected => 113,
            Self::DocumentRejected => 114,
            Self::FilterRejected => 115,
            Self::BinaryDataRejected => 116,
            Self::SelectionRejected => 117,
            Self::WriteRejected => 118,
            Self::CloseRejected => 119,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };
    let Ok(document_revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if document_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    let Ok(filter) = FileDialogFilter::new("Binary files", vec!["bin".to_owned()]) else {
        return Stage::FilterRejected;
    };
    let Ok(data) = FileBinaryData::decode_base64url(BINARY_BASE64URL) else {
        return Stage::BinaryDataRejected;
    };
    if data.as_bytes() != BINARY_BYTES {
        return Stage::BinaryDataRejected;
    }
    match session.select_save_file_v2(&[filter]) {
        Ok(SaveSelectionResult::Selected(selection)) => {
            if session
                .write_selected_binary(selection.reference(), &data)
                .is_err()
            {
                return Stage::WriteRejected;
            }
        }
        Ok(SaveSelectionResult::Cancelled) => {}
        Err(_) => return Stage::SelectionRejected,
    }
    if session.close().is_ok() {
        Stage::Completed
    } else {
        Stage::CloseRejected
    }
}
"##;

#[cfg(test)]
mod tests {
    use super::{BINARY_BASE64URL, BINARY_BYTES, document_json, main_source};

    #[test]
    fn fixed_source_uses_one_canonical_retained_binary_output() {
        assert!(anodrel_ui_document::decode(&document_json("Binary Write App")).is_ok());
        let source = main_source("Binary Write App");
        assert!(source.contains("FileBinaryData::decode_base64url(BINARY_BASE64URL)"));
        assert!(source.contains("write_selected_binary(selection.reference(), &data)"));
        assert!(source.contains("SaveSelectionResult::Cancelled"));
        assert!(!source.contains("std::fs"));
        assert!(!source.contains("read_actions"));
        assert!(!source.contains("write_selected_text"));
        assert_eq!(
            anodrel_file_access::FileBinaryData::decode_base64url(BINARY_BASE64URL)
                .expect("fixed value is canonical")
                .as_bytes(),
            BINARY_BYTES
        );
    }
}
