//! Fixed source for the explicit native form template.

use super::{TemplateContext, json_string, quoted, windows_path};

pub(super) fn main_source(display_label: &str) -> String {
    format!(
        "{MAIN_PREFIX}{}{MAIN_SUFFIX}",
        quoted(&document(display_label)),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel form template\n\nThis is a small Windows native form project generated by anodrel-native-app-tool. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed document containing an editable Name field. After a person activates Submit form, it asks for the one whole-surface field snapshot, verifies the expected field shape without displaying the entered value, then closes its own session. It contains no raw protocol envelopes, host policy, capability declaration, OS window handle, keyboard input, package identity, configuration loader, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n~~~powershell\ncargo build --release\n~~~\n\nThis produces target\\release\\{project_slug}.exe. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit native-form development route:\n\n~~~powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-form-template-client $clientPath\n~~~\n\nThe host opens an Anodrel Native Form Template window. Enter ordinary non-secret text in Name, then activate Submit form. The host grants exactly document replacement, semantic-action reading, whole-surface field read, and self-close. It ignores any project-supplied capability, identity, native control, keyboard setting, field selector, or window setting.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.form.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.form.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE FORM TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.form.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.form.detail\",\"kind\":\"text\",\"value\":\"Your text stays with the host until you explicitly submit this form.\",\"fontSize\":16,\"tone\":\"secondary\"}},{{\"id\":\"template.form.name\",\"kind\":\"field\",\"label\":\"Name\",\"value\":\"\",\"placeholder\":\"Enter your name\",\"maxLength\":96,\"fontSize\":16,\"enabled\":true}},{{\"id\":\"template.form.submit\",\"kind\":\"action\",\"label\":\"Submit form\",\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel form template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, reads one typed whole-surface
//! field snapshot after explicit submission, and never selects host authority.

use std::{process::ExitCode, thread};

use anodrel_windows_ui_sdk::{
    InteractivePollSchedule, WindowsUiConnectionError, WindowsUiSession,
};

const SUBMIT_ACTION: &str = "template.form.submit";
const NAME_FIELD: &str = "template.form.name";
const DOCUMENT: &str = "##;

const MAIN_SUFFIX: &str = r##";


#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    EventReadFailed,
    ActionNotObserved,
    FieldReadFailed,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 81,
            Self::EndpointUnavailable => 82,
            Self::AuthenticationRejected => 83,
            Self::DocumentRejected => 84,
            Self::EventReadFailed => 85,
            Self::ActionNotObserved => 86,
            Self::FieldReadFailed => 87,
            Self::CloseRejected => 88,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };
    let Ok(revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    let mut submitted = false;
    for interval in InteractivePollSchedule::new() {
        let Ok(batch) = session.read_actions() else {
            return Stage::EventReadFailed;
        };
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Stage::EventReadFailed;
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            [action]
                if action.action() == SUBMIT_ACTION && action.revision().value() == 1 => {
                    submitted = true;
                    break;
                }
            _ => return Stage::EventReadFailed,
        }
    }
    if !submitted {
        return Stage::ActionNotObserved;
    }
    let Ok(snapshot) = session.read_fields() else {
        return Stage::FieldReadFailed;
    };
    let [field] = snapshot.fields() else {
        return Stage::FieldReadFailed;
    };
    if field.id().as_str() != NAME_FIELD || field.value().chars().count() > 96 {
        return Stage::FieldReadFailed;
    }
    if session.close().is_err() {
        return Stage::CloseRejected;
    }
    Stage::Completed
}
"##;

#[cfg(test)]
mod tests {
    use super::document;

    #[test]
    fn fixed_form_document_uses_the_strict_v1_contract() {
        let document = document("Generated Form Template");
        let decoded =
            anodrel_ui_document::decode(&document).expect("fixed form document is strict v1");
        assert_eq!(decoded.root().id().as_str(), "template.form.root");
    }
}
