//! Fixed source for the explicit native live-status template.

use super::{TemplateContext, json_string, quoted, windows_path};

pub(super) fn main_source(display_label: &str) -> String {
    let initial = document(
        display_label,
        "Ready to publish a visible result.",
        "polite",
        "template.status.polite",
        "Publish polite result",
    );
    let polite = document(
        display_label,
        "Verification is complete.",
        "polite",
        "template.status.assertive",
        "Publish assertive result",
    );
    let assertive = document(
        display_label,
        "Verification succeeded.",
        "assertive",
        "template.status.complete",
        "Complete status session",
    );
    format!(
        "{MAIN_PREFIX}{};\nconst POLITE_DOCUMENT: &str = {};\nconst ASSERTIVE_DOCUMENT: &str = {}{MAIN_SUFFIX}",
        quoted(&initial),
        quoted(&polite),
        quoted(&assertive),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel live-status template\n\nThis is a small Windows native live-status project generated by anodrel-native-app-tool. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits three fixed version-3 documents. A person chooses each next visible result: a polite status, then an assertive status, then session completion. It never receives an accessibility callback or delivery result. It contains no raw protocol envelopes, host policy, capability declaration, OS window handle, UI Automation identifier, notification route, package identity, configuration loader, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n~~~powershell\ncargo build --release\n~~~\n\nThis produces target\\release\\{project_slug}.exe. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit native live-status development route:\n\n~~~powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-live-status-template-client $clientPath\n~~~\n\nThe host opens an Anodrel Native Live Status Template window. Start Narrator after the window opens, then activate Publish polite result, Publish assertive result, and Complete status session in order. The host grants exactly version-3 document replacement, semantic-action reading, and self-close. The program receives only accepted revisions and semantic actions; it cannot learn whether assistive technology announced either status.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document(
    display_label: &str,
    status: &str,
    politeness: &str,
    action: &str,
    action_label: &str,
) -> String {
    let label = json_string(display_label);
    let status = json_string(status);
    let action = json_string(action);
    let action_label = json_string(action_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v3\",\"root\":{{\"id\":\"template.status.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.status.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE LIVE STATUS TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.status.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.status.detail\",\"kind\":\"text\",\"value\":\"Each visible result is a complete version-3 document. An accessibility announcement is outbound and best effort.\",\"fontSize\":16,\"tone\":\"secondary\"}},{{\"id\":\"template.status.result\",\"kind\":\"status\",\"value\":{status},\"fontSize\":16,\"tone\":\"accent\",\"politeness\":\"{politeness}\"}},{{\"id\":{action},\"kind\":\"action\",\"label\":{action_label},\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel live-status template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the typed version-3
//! document surface, and never selects host capabilities or observes assistive
//! technology.

use std::{io, process::ExitCode, thread};

use anodrel_client::{Client, InteractivePollSchedule};
use anodrel_ui_client::UiSession;
use anodrel_windows_client::WindowsClientStream;

const POLITE_ACTION: &str = "template.status.polite";
const ASSERTIVE_ACTION: &str = "template.status.assertive";
const COMPLETE_ACTION: &str = "template.status.complete";
const INITIAL_DOCUMENT: &str = "##;

const MAIN_SUFFIX: &str = r##";

type NativeUiClient = Client<WindowsClientStream>;

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    EventReadFailed,
    ActionNotObserved,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 91,
            Self::EndpointUnavailable => 92,
            Self::AuthenticationRejected => 93,
            Self::DocumentRejected => 94,
            Self::EventReadFailed => 95,
            Self::ActionNotObserved => 96,
            Self::CloseRejected => 97,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let Ok(invitation) = NativeUiClient::read_invitation(&mut io::stdin()) else {
        return Stage::BootstrapUnreadable;
    };
    let Ok(stream) = WindowsClientStream::connect(&invitation) else {
        return Stage::EndpointUnavailable;
    };
    let Ok(client) = NativeUiClient::authenticate(stream, invitation) else {
        return Stage::AuthenticationRejected;
    };
    let mut session = UiSession::new(client);

    let Ok(revision) = session.replace_document_v3(INITIAL_DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    if let Err(stage) = wait_for_action(&mut session, POLITE_ACTION, revision.value()) {
        return stage;
    }

    let Ok(revision) = session.replace_document_v3(POLITE_DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if revision.value() != 2 {
        return Stage::DocumentRejected;
    }
    if let Err(stage) = wait_for_action(&mut session, ASSERTIVE_ACTION, revision.value()) {
        return stage;
    }

    let Ok(revision) = session.replace_document_v3(ASSERTIVE_DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if revision.value() != 3 {
        return Stage::DocumentRejected;
    }
    if let Err(stage) = wait_for_action(&mut session, COMPLETE_ACTION, revision.value()) {
        return stage;
    }

    if session.close().is_err() {
        return Stage::CloseRejected;
    }
    Stage::Completed
}

fn wait_for_action(
    session: &mut UiSession<WindowsClientStream>,
    expected_action: &str,
    expected_revision: u64,
) -> Result<(), Stage> {
    for interval in InteractivePollSchedule::new() {
        let batch = session.read_actions().map_err(|_| Stage::EventReadFailed)?;
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Err(Stage::EventReadFailed);
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            [action]
                if action.action() == expected_action
                    && action.revision().value() == expected_revision =>
            {
                return Ok(());
            }
            _ => return Err(Stage::EventReadFailed),
        }
    }
    Err(Stage::ActionNotObserved)
}
"##;

#[cfg(test)]
mod tests {
    use super::document;

    #[test]
    fn fixed_live_status_documents_use_the_strict_v3_contract() {
        let document = document(
            "Generated Live Status Template",
            "Ready",
            "polite",
            "template.status.polite",
            "Publish polite result",
        );
        let decoded = anodrel_ui_document::decode_v3(&document)
            .expect("fixed live-status document is strict v3");
        assert_eq!(decoded.root().id().as_str(), "template.status.root");
        assert_eq!(decoded.status().map(|status| status.value()), Some("Ready"));
    }
}
