//! Fixed source and documentation for the bounded native-menu template.

use super::{TemplateContext, json_string, quoted, windows_path};

const MENU: &str = r#"{"menus":[{"label":"File","items":[{"id":"template.menu.complete","label":"Complete menu template session","enabled":true,"shortcut":"Ctrl+Shift+M"}]}]}"#;

pub(super) fn main_source(display_label: &str) -> String {
    let document = document_json(display_label);
    format!(
        "{MAIN_PREFIX}{}{MAIN_MIDDLE}{}{MAIN_SUFFIX}",
        quoted(&document),
        quoted(MENU),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel menu template\n\nThis is a small Windows native menu project generated by `anodrel-native-app-tool`. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed Anodrel document and one complete native menu model. It waits for its one semantic menu action, then requests that its own host-created session closes. It contains no raw protocol envelopes, host policy, capability declaration, OS window handle, package identity, configuration loader, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n```powershell\ncargo build --release\n```\n\nThis produces `target\\release\\{project_slug}.exe`. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit native-menu development route:\n\n```powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-menu-template-client $clientPath\n```\n\nThe host opens an **Anodrel Native Menu Template** window. Choose **File > Complete menu template session** or press **Ctrl+Shift+M** to let this executable close only its own session. The host grants exactly document replacement, semantic-action reading, native menu replacement, and self-close; it ignores any project-supplied capability, identity, title, menu handle, command number, shortcut, or window setting.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document_json(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.menu.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.menu.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE MENU TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.menu.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.menu.detail\",\"kind\":\"text\",\"value\":\"Use File > Complete menu template session or Ctrl+Shift+M to return one typed native menu action.\",\"fontSize\":16,\"tone\":\"secondary\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel menu template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the typed menu surface,
//! and never selects host capabilities or native window resources.

use std::{io, process::ExitCode, thread};

use anodrel_client::{Client, InteractivePollSchedule};
use anodrel_ui_client::{UiEvent, UiSession};
use anodrel_windows_client::WindowsClientStream;

const COMPLETE_ACTION: &str = "template.menu.complete";
const DOCUMENT: &str = "##;

const MAIN_MIDDLE: &str = r##";
const MENU: &str = "##;

const MAIN_SUFFIX: &str = r##";

type NativeUiClient = Client<WindowsClientStream>;

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    MenuRejected,
    EventReadFailed,
    ActionNotObserved,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 61,
            Self::EndpointUnavailable => 62,
            Self::AuthenticationRejected => 63,
            Self::DocumentRejected => 64,
            Self::MenuRejected => 65,
            Self::EventReadFailed => 66,
            Self::ActionNotObserved => 67,
            Self::CloseRejected => 68,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let Ok(invitation) = NativeUiClient::read_invitation(&mut io::stdin()) else {
        return Stage::BootstrapUnreadable;
    };
    let Ok(stream) = WindowsClientStream::connect(&invitation) else {
        return Stage::EndpointUnavailable;
    };
    let Ok(client) = NativeUiClient::authenticate(stream, invitation) else {
        return Stage::AuthenticationRejected;
    };
    let mut session = UiSession::new(client);
    let Ok(document_revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if document_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    let Ok(menu_revision) = session.replace_menu_v1(MENU) else {
        return Stage::MenuRejected;
    };
    if menu_revision.value() != 1 {
        return Stage::MenuRejected;
    }
    for interval in InteractivePollSchedule::new() {
        let Ok(batch) = session.read_events() else {
            return Stage::EventReadFailed;
        };
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Stage::EventReadFailed;
        }
        match batch.events() {
            [] => thread::sleep(interval),
            [UiEvent::MenuAction(action)]
                if action.action() == COMPLETE_ACTION && action.revision().value() == 1 =>
            {
                return if session.close().is_ok() {
                    Stage::Completed
                } else {
                    Stage::CloseRejected
                };
            }
            _ => return Stage::EventReadFailed,
        }
    }
    Stage::ActionNotObserved
}
"##;

#[cfg(test)]
mod tests {
    use super::{MENU, document_json};

    #[test]
    fn fixed_menu_source_keeps_one_exact_enabled_action() {
        assert!(MENU.contains("template.menu.complete"));
        assert!(MENU.contains(r#""shortcut":"Ctrl+Shift+M""#));
        assert!(anodrel_ui_document::decode(&document_json("Menu App")).is_ok());
    }
}
