//! Fixed generated source for the explicit native multi-window template.

use super::{TemplateContext, json_string, quoted, windows_path};

pub(super) fn main_source(display_label: &str) -> String {
    let primary = primary_document(display_label);
    let secondary_waiting = secondary_waiting_document();
    let secondary_complete = secondary_complete_document();
    format!(
        "{MAIN_PREFIX}{};\nconst SECONDARY_WAITING_DOCUMENT: &str = {};\nconst SECONDARY_COMPLETE_DOCUMENT: &str = {}{MAIN_SUFFIX}",
        quoted(&primary),
        quoted(&secondary_waiting),
        quoted(&secondary_complete),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel multi-window template\n\nThis is a small Windows native project generated by anodrel-native-app-tool. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program visibly walks through Anodrel's bounded session-owned multi-window API: a primary action opens a secondary view; its first action replaces that secondary document; its second action closes that exact secondary view and then closes the session. It contains no raw protocol envelopes, host policy, capability declaration, native handle, package identity, configuration loader, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n~~~powershell\ncargo build --release\n~~~\n\nThis produces target\\release\\{project_slug}.exe. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit multi-window development route:\n\n~~~powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-multi-window-template-client $clientPath\n~~~\n\nThe host opens an Anodrel Native Multi-Window Template primary window. Activate Open secondary window, then in the separate secondary window activate Replace this window and finally Close secondary and finish. The host grants exactly document replacement, tagged semantic-action reading, bounded secondary open and close, and self-close. It ignores any project-supplied capability, identity, native handle, geometry, or host setting.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn primary_document(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL MULTI-WINDOW TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.detail\",\"kind\":\"text\",\"value\":\"Open a bounded secondary view to begin the typed walkthrough.\",\"fontSize\":16,\"tone\":\"secondary\"}},{{\"id\":\"template.window.open\",\"kind\":\"action\",\"label\":\"Open secondary window\",\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}"
    )
}

fn secondary_waiting_document() -> String {
    "{\"format\":\"anodrel.ui.document.v1\",\"root\":{\"id\":\"template.secondary.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{\"id\":\"template.secondary.eyebrow\",\"kind\":\"text\",\"value\":\"SECONDARY VIEW\",\"fontSize\":14,\"tone\":\"accent\"},{\"id\":\"template.secondary.detail\",\"kind\":\"text\",\"value\":\"This action replaces only this window's document.\",\"fontSize\":16,\"tone\":\"secondary\"},{\"id\":\"template.window.update\",\"kind\":\"action\",\"label\":\"Replace this window\",\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}]}}"
        .to_owned()
}

fn secondary_complete_document() -> String {
    "{\"format\":\"anodrel.ui.document.v1\",\"root\":{\"id\":\"template.secondary.complete.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{\"id\":\"template.secondary.complete.eyebrow\",\"kind\":\"text\",\"value\":\"SECONDARY UPDATED\",\"fontSize\":14,\"tone\":\"accent\"},{\"id\":\"template.secondary.complete.detail\",\"kind\":\"text\",\"value\":\"This final action closes this secondary view, then the session.\",\"fontSize\":16,\"tone\":\"secondary\"},{\"id\":\"template.window.complete\",\"kind\":\"action\",\"label\":\"Close secondary and finish\",\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}]}}"
        .to_owned()
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel multi-window template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the typed fixed
//! multi-window client surface, and never selects host capabilities or native
//! window resources.

use std::{io, process::ExitCode, thread};

use anodrel_client::{Client, InteractivePollSchedule};
use anodrel_ui_client::{SessionWindowId, UiSession};
use anodrel_windows_client::WindowsClientStream;

const PRIMARY_OPEN_ACTION: &str = "template.window.open";
const SECONDARY_UPDATE_ACTION: &str = "template.window.update";
const SECONDARY_COMPLETE_ACTION: &str = "template.window.complete";
const SECONDARY_TITLE: &str = "Template secondary";
const PRIMARY_DOCUMENT: &str = "##;

const MAIN_SUFFIX: &str = r##";

type NativeUiClient = Client<WindowsClientStream>;

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    WindowOpenRejected,
    WindowUpdateRejected,
    EventReadFailed,
    ActionNotObserved,
    WindowCloseRejected,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 71,
            Self::EndpointUnavailable => 72,
            Self::AuthenticationRejected => 73,
            Self::DocumentRejected => 74,
            Self::WindowOpenRejected => 75,
            Self::WindowUpdateRejected => 76,
            Self::EventReadFailed => 77,
            Self::ActionNotObserved => 78,
            Self::WindowCloseRejected => 79,
            Self::CloseRejected => 80,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let Ok(invitation) = NativeUiClient::read_invitation(&mut io::stdin()) else {
        return Stage::BootstrapUnreadable;
    };
    let Ok(stream) = WindowsClientStream::connect(&invitation) else {
        return Stage::EndpointUnavailable;
    };
    let Ok(client) = NativeUiClient::authenticate(stream, invitation) else {
        return Stage::AuthenticationRejected;
    };
    let mut session = UiSession::new(client);
    let Ok(primary_revision) = session.replace_document_v1(PRIMARY_DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if primary_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    if let Err(stage) = wait_for_action(
        &mut session,
        SessionWindowId::Main,
        PRIMARY_OPEN_ACTION,
        primary_revision.value(),
    ) {
        return stage;
    }
    let Ok(secondary) = session.open_window_v1(SECONDARY_TITLE, SECONDARY_WAITING_DOCUMENT) else {
        return Stage::WindowOpenRejected;
    };
    if let Err(stage) = wait_for_action(
        &mut session,
        SessionWindowId::Secondary(secondary),
        SECONDARY_UPDATE_ACTION,
        1,
    ) {
        return stage;
    }
    let Ok(secondary_revision) =
        session.replace_window_document_v1(secondary, SECONDARY_COMPLETE_DOCUMENT)
    else {
        return Stage::WindowUpdateRejected;
    };
    if secondary_revision.value() != 2 {
        return Stage::WindowUpdateRejected;
    }
    if let Err(stage) = wait_for_action(
        &mut session,
        SessionWindowId::Secondary(secondary),
        SECONDARY_COMPLETE_ACTION,
        secondary_revision.value(),
    ) {
        return stage;
    }
    if session.close_window(secondary).is_err() {
        return Stage::WindowCloseRejected;
    }
    if session.close().is_err() {
        return Stage::CloseRejected;
    }
    Stage::Completed
}

fn wait_for_action(
    session: &mut UiSession<WindowsClientStream>,
    expected_window: SessionWindowId,
    expected_action: &str,
    expected_revision: u64,
) -> Result<(), Stage> {
    for interval in InteractivePollSchedule::new() {
        let batch = session.read_window_actions().map_err(|_| Stage::EventReadFailed)?;
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Err(Stage::EventReadFailed);
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            [action]
                if action.window() == expected_window
                    && action.action().action() == expected_action
                    && action.action().revision().value() == expected_revision => return Ok(()),
            _ => return Err(Stage::EventReadFailed),
        }
    }
    Err(Stage::ActionNotObserved)
}
"##;

#[cfg(test)]
mod tests {
    use super::{primary_document, secondary_complete_document, secondary_waiting_document};

    #[test]
    fn every_fixed_walkthrough_document_uses_the_strict_v1_contract() {
        for (name, document) in [
            (
                "primary",
                primary_document("Generated Multi-Window Template"),
            ),
            ("secondary waiting", secondary_waiting_document()),
            ("secondary complete", secondary_complete_document()),
        ] {
            anodrel_ui_document::decode(&document)
                .unwrap_or_else(|error| panic!("{name} generated document is invalid: {error}"));
        }
    }
}
