//! Fixed source and documentation for the bounded native notification template.

use super::{TemplateContext, json_string, quoted, windows_path};

const NOTIFICATION_TITLE: &str = "Anodrel native notification";
const NOTIFICATION_BODY: &str =
    "The direct Windows notification route accepted this fixed template request.";

pub(super) fn main_source(display_label: &str) -> String {
    let document = document_json(display_label);
    format!(
        "{MAIN_PREFIX}{}{MAIN_DOCUMENT_TO_TITLE}{}{MAIN_TITLE_TO_BODY}{}{MAIN_SUFFIX}",
        quoted(&document),
        quoted(NOTIFICATION_TITLE),
        quoted(NOTIFICATION_BODY),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel notification template\n\nThis small Windows-native project is generated by `anodrel-native-app-tool`. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed Anodrel document, asks the host to hand one fixed notification to Windows, waits five seconds so an operator can see the desktop result, then requests only its own host-created session close. It has no raw protocol envelope, host policy, capability declaration, notification ID, callback, action, icon, toast identity, native window handle, network access, package identity, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n```powershell\ncargo build --release\n```\n\nThis produces `target\\release\\{project_slug}.exe`. It is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit notification development route:\n\n```powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-notification-template-client $clientPath\n```\n\nThe host opens an **Anodrel Native Notification Template** window, hands one fixed title and body to Shell32, and keeps the session open for five seconds. Look for the notification while the window remains open. Completion means Windows accepted the request, not that the host or this project knows whether anyone saw it. Windows may attribute the notification to `anodrel-windows-host.exe` until Anodrel has a production Application User Model ID.\n\nThe host grants exactly document replacement, notification showing, and self-close. It owns the Shell32 entry, icon, hover text, callback, application attribution, private pipe, and cleanup.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document_json(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.notification.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.notification.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE NOTIFICATION TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.notification.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.notification.detail\",\"kind\":\"text\",\"value\":\"A fixed native notification will be requested. This session closes five seconds after Windows accepts it.\",\"fontSize\":16,\"tone\":\"secondary\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel notification template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the typed one-way
//! notification surface, and never selects host capabilities or native
//! notification-area resources.

use std::{process::ExitCode, thread, time::Duration};

use anodrel_windows_ui_sdk::{WindowsUiConnectionError, WindowsUiSession};

const DOCUMENT: &str = "##;

const MAIN_DOCUMENT_TO_TITLE: &str = r##";
const NOTIFICATION_TITLE: &str = "##;

const MAIN_TITLE_TO_BODY: &str = r##";
const NOTIFICATION_BODY: &str = "##;

const MAIN_SUFFIX: &str = r##";

const OBSERVATION_DELAY: Duration = Duration::from_secs(5);

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    NotificationRejected,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 91,
            Self::EndpointUnavailable => 92,
            Self::AuthenticationRejected => 93,
            Self::DocumentRejected => 94,
            Self::NotificationRejected => 95,
            Self::CloseRejected => 96,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };
    let Ok(document_revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if document_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    if session
        .show_notification(NOTIFICATION_TITLE, NOTIFICATION_BODY)
        .is_err()
    {
        return Stage::NotificationRejected;
    }
    thread::sleep(OBSERVATION_DELAY);
    if session.close().is_ok() {
        Stage::Completed
    } else {
        Stage::CloseRejected
    }
}
"##;

#[cfg(test)]
mod tests {
    use super::{NOTIFICATION_BODY, NOTIFICATION_TITLE, document_json, main_source};

    #[test]
    fn fixed_notification_source_keeps_the_one_way_surface() {
        assert!(anodrel_ui_document::decode(&document_json("Notification App")).is_ok());
        let source = main_source("Notification App");
        assert!(source.contains("show_notification(NOTIFICATION_TITLE, NOTIFICATION_BODY)"));
        assert!(source.contains("Duration::from_secs(5)"));
        assert!(!source.contains("read_actions"));
        assert!(!source.contains("replace_tray_v1"));
        assert!(NOTIFICATION_TITLE.len() <= 63);
        assert!(NOTIFICATION_BODY.len() <= 255);
    }
}
