//! Fixed generated source for the explicit native scroll-window template.

use super::{TemplateContext, json_string, quoted, windows_path};

const CHECKPOINT_COUNT: usize = 30;

pub(super) fn main_source(display_label: &str) -> String {
    let primary = primary_document(display_label);
    let secondary_waiting = secondary_document(
        "SCROLLABLE SECONDARY VIEW",
        "Scroll locally to reach the action below. The host retains this view's position.",
        "template.scroll.reveal",
        "Reveal updated scroll document",
    );
    let secondary_complete = secondary_document(
        "SECONDARY DOCUMENT UPDATED",
        "This is revision two of the same scrollable secondary view. Scroll to finish.",
        "template.scroll.complete",
        "Close secondary and finish",
    );
    format!(
        "{MAIN_PREFIX}{};\nconst SECONDARY_WAITING_DOCUMENT: &str = {};\nconst SECONDARY_COMPLETE_DOCUMENT: &str = {};{MAIN_SUFFIX}",
        quoted(&primary),
        quoted(&secondary_waiting),
        quoted(&secondary_complete),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel scroll-window template\n\nThis is a small Windows native project generated by anodrel-native-app-tool. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program visibly walks through Anodrel's bounded secondary scroll-document API: a primary action opens a strict version-2 secondary view; local host-owned scrolling reveals an action that replaces only that view; local scrolling reveals one final action that closes the secondary and then the session. It contains no raw protocol envelopes, host policy, capability declaration, native handle, scroll position, package identity, configuration loader, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n~~~powershell\ncargo build --release\n~~~\n\nThis produces target\\release\\{project_slug}.exe. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit scroll-window development route:\n\n~~~powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-scroll-window-template-client $clientPath\n~~~\n\nThe host opens an Anodrel Native Scroll Window Template primary window. Activate Open scrollable secondary window. In the separate secondary window, scroll until Reveal updated scroll document appears and activate it. Then scroll the replacement document until Close secondary and finish appears. The host grants exactly document replacement, tagged semantic-action reading, bounded secondary open and close, and self-close. It keeps scroll state, native input, accessibility scrolling, geometry, and private mappings out of the generated executable.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn primary_document(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.scroll.primary.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.scroll.primary.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL SCROLL-WINDOW TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.scroll.primary.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.scroll.primary.detail\",\"kind\":\"text\",\"value\":\"Open a bounded scrollable secondary view to begin the typed walkthrough.\",\"fontSize\":16,\"tone\":\"secondary\"}},{{\"id\":\"template.scroll.open\",\"kind\":\"action\",\"label\":\"Open scrollable secondary window\",\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}"
    )
}

fn secondary_document(heading: &str, detail: &str, action: &str, action_label: &str) -> String {
    let heading = json_string(heading);
    let detail = json_string(detail);
    let action = json_string(action);
    let action_label = json_string(action_label);
    let checkpoints = (1..=CHECKPOINT_COUNT)
        .map(|number| {
            format!(
                "{{\"id\":\"template.scroll.checkpoint.{number}\",\"kind\":\"text\",\"value\":\"Host-owned scroll checkpoint {number} of {CHECKPOINT_COUNT}.\",\"fontSize\":18,\"tone\":\"secondary\"}}"
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "{{\"format\":\"anodrel.ui.document.v2\",\"root\":{{\"id\":\"template.scroll.viewport\",\"kind\":\"scroll\",\"child\":{{\"id\":\"template.scroll.content\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":96}},\"gap\":20,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.scroll.eyebrow\",\"kind\":\"text\",\"value\":{heading},\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.scroll.detail\",\"kind\":\"text\",\"value\":{detail},\"fontSize\":18,\"tone\":\"primary\"}},{checkpoints},{{\"id\":{action},\"kind\":\"action\",\"label\":{action_label},\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel scroll-window template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the explicit version-2
//! secondary-document client methods, and never selects host capabilities or
//! observes native scroll state.

use std::{io, process::ExitCode, thread};

use anodrel_client::{Client, InteractivePollSchedule};
use anodrel_ui_client::{SessionWindowId, UiSession};
use anodrel_windows_client::WindowsClientStream;

const PRIMARY_OPEN_ACTION: &str = "template.scroll.open";
const SECONDARY_REVEAL_ACTION: &str = "template.scroll.reveal";
const SECONDARY_COMPLETE_ACTION: &str = "template.scroll.complete";
const SECONDARY_TITLE: &str = "Template scrollable secondary";
const PRIMARY_DOCUMENT: &str = "##;

const MAIN_SUFFIX: &str = r##"

type NativeUiClient = Client<WindowsClientStream>;

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    WindowOpenRejected,
    WindowUpdateRejected,
    EventReadFailed,
    ActionNotObserved,
    WindowCloseRejected,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 101,
            Self::EndpointUnavailable => 102,
            Self::AuthenticationRejected => 103,
            Self::DocumentRejected => 104,
            Self::WindowOpenRejected => 105,
            Self::WindowUpdateRejected => 106,
            Self::EventReadFailed => 107,
            Self::ActionNotObserved => 108,
            Self::WindowCloseRejected => 109,
            Self::CloseRejected => 110,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let Ok(invitation) = NativeUiClient::read_invitation(&mut io::stdin()) else {
        return Stage::BootstrapUnreadable;
    };
    let Ok(stream) = WindowsClientStream::connect(&invitation) else {
        return Stage::EndpointUnavailable;
    };
    let Ok(client) = NativeUiClient::authenticate(stream, invitation) else {
        return Stage::AuthenticationRejected;
    };
    let mut session = UiSession::new(client);
    let Ok(primary_revision) = session.replace_document_v1(PRIMARY_DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if primary_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    if let Err(stage) = wait_for_action(
        &mut session,
        SessionWindowId::Main,
        PRIMARY_OPEN_ACTION,
        primary_revision.value(),
    ) {
        return stage;
    }
    let Ok(secondary) = session.open_window_v2(SECONDARY_TITLE, SECONDARY_WAITING_DOCUMENT) else {
        return Stage::WindowOpenRejected;
    };
    if let Err(stage) = wait_for_action(
        &mut session,
        SessionWindowId::Secondary(secondary),
        SECONDARY_REVEAL_ACTION,
        1,
    ) {
        return stage;
    }
    let Ok(secondary_revision) =
        session.replace_window_document_v2(secondary, SECONDARY_COMPLETE_DOCUMENT)
    else {
        return Stage::WindowUpdateRejected;
    };
    if secondary_revision.value() != 2 {
        return Stage::WindowUpdateRejected;
    }
    if let Err(stage) = wait_for_action(
        &mut session,
        SessionWindowId::Secondary(secondary),
        SECONDARY_COMPLETE_ACTION,
        secondary_revision.value(),
    ) {
        return stage;
    }
    if session.close_window(secondary).is_err() {
        return Stage::WindowCloseRejected;
    }
    if session.close().is_err() {
        return Stage::CloseRejected;
    }
    Stage::Completed
}

fn wait_for_action(
    session: &mut UiSession<WindowsClientStream>,
    expected_window: SessionWindowId,
    expected_action: &str,
    expected_revision: u64,
) -> Result<(), Stage> {
    for interval in InteractivePollSchedule::new() {
        let batch = session.read_window_actions().map_err(|_| Stage::EventReadFailed)?;
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Err(Stage::EventReadFailed);
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            [action]
                if action.window() == expected_window
                    && action.action().action() == expected_action
                    && action.action().revision().value() == expected_revision => return Ok(()),
            _ => return Err(Stage::EventReadFailed),
        }
    }
    Err(Stage::ActionNotObserved)
}
"##;

#[cfg(test)]
mod tests {
    use super::{primary_document, secondary_document};

    #[test]
    fn fixed_walkthrough_documents_keep_v1_primary_and_v2_secondary_boundaries() {
        let primary = primary_document("Generated Scroll Window Template");
        anodrel_ui_document::decode(&primary).expect("fixed primary document is strict v1");

        for (name, document) in [
            (
                "secondary waiting",
                secondary_document(
                    "SCROLLABLE SECONDARY VIEW",
                    "Scroll locally.",
                    "template.scroll.reveal",
                    "Reveal updated scroll document",
                ),
            ),
            (
                "secondary complete",
                secondary_document(
                    "SECONDARY DOCUMENT UPDATED",
                    "Scroll locally again.",
                    "template.scroll.complete",
                    "Close secondary and finish",
                ),
            ),
        ] {
            let decoded = anodrel_ui_document::decode_v2(&document)
                .unwrap_or_else(|error| panic!("{name} generated document is invalid: {error}"));
            assert_eq!(decoded.root().id().as_str(), "template.scroll.viewport");
            assert!(matches!(decoded.root(), anodrel_ui::UiNode::Scroll(_)));
        }
    }
}
