//! Fixed source and documentation for the bounded native tray template.

use super::{TemplateContext, json_string, quoted, windows_path};

const TRAY: &str = r#"{"items":[{"id":"template.tray.complete","label":"Complete tray template session","enabled":true}]}"#;

pub(super) fn main_source(display_label: &str) -> String {
    let document = document_json(display_label);
    format!(
        "{MAIN_PREFIX}{}{MAIN_MIDDLE}{}{MAIN_SUFFIX}",
        quoted(&document),
        quoted(TRAY),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel tray template\n\nThis small Windows-native project is generated by `anodrel-native-app-tool`. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program submits one fixed Anodrel document and one complete semantic tray menu. It waits for one local notification-area action and then requests that its own host-created session closes. It has no raw protocol envelope, host policy, capability declaration, icon, tooltip, callback, pointer location, native window handle, command number, background behavior, network access, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n```powershell\ncargo build --release\n```\n\nThis produces `target\\release\\{project_slug}.exe`. It is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit tray development route:\n\n```powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-tray-template-client $clientPath\n```\n\nThe host opens an **Anodrel Native Tray Template** window and creates its one host-selected notification-area icon after the model is accepted. Right-click the icon, then choose **Complete tray template session**. The host owns the icon, tooltip, callback, cursor position, User32 popup, private command, and event route. The template receives only one revision-bound semantic action. The host grants exactly document replacement, semantic-action reading, tray replacement, and self-close.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document_json(display_label: &str) -> String {
    let label = json_string(display_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.tray.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.tray.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL NATIVE TRAY TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.tray.title\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.tray.detail\",\"kind\":\"text\",\"value\":\"Right-click Anodrel's notification-area icon, then choose Complete tray template session.\",\"fontSize\":16,\"tone\":\"secondary\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel tray template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the typed tray surface,
//! and never selects host capabilities or notification-area resources.

use std::{process::ExitCode, thread};

use anodrel_windows_ui_sdk::{
    InteractivePollSchedule, WindowsUiConnectionError, WindowsUiSession,
};

const COMPLETE_ACTION: &str = "template.tray.complete";
const DOCUMENT: &str = "##;

const MAIN_MIDDLE: &str = r##";
const TRAY: &str = "##;

const MAIN_SUFFIX: &str = r##";

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    TrayRejected,
    EventReadFailed,
    ActionNotObserved,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 81,
            Self::EndpointUnavailable => 82,
            Self::AuthenticationRejected => 83,
            Self::DocumentRejected => 84,
            Self::TrayRejected => 85,
            Self::EventReadFailed => 86,
            Self::ActionNotObserved => 87,
            Self::CloseRejected => 88,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };
    let Ok(document_revision) = session.replace_document_v1(DOCUMENT) else {
        return Stage::DocumentRejected;
    };
    if document_revision.value() != 1 {
        return Stage::DocumentRejected;
    }
    let Ok(tray_revision) = session.replace_tray_v1(TRAY) else {
        return Stage::TrayRejected;
    };
    if tray_revision.value() != 1 {
        return Stage::TrayRejected;
    }
    for interval in InteractivePollSchedule::new() {
        let Ok(batch) = session.read_tray_actions() else {
            return Stage::EventReadFailed;
        };
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Stage::EventReadFailed;
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            [action]
                if action.action() == COMPLETE_ACTION && action.revision().value() == 1 =>
            {
                return if session.close().is_ok() {
                    Stage::Completed
                } else {
                    Stage::CloseRejected
                };
            }
            _ => return Stage::EventReadFailed,
        }
    }
    Stage::ActionNotObserved
}
"##;

#[cfg(test)]
mod tests {
    use super::{TRAY, document_json, main_source};

    #[test]
    fn fixed_tray_source_keeps_one_exact_enabled_action() {
        assert!(TRAY.contains("template.tray.complete"));
        assert!(anodrel_ui_document::decode(&document_json("Tray App")).is_ok());
        let source = main_source("Tray App");
        let tray_declaration = source
            .split_once("const TRAY: &str = ")
            .expect("generated source declares its fixed tray model")
            .1;
        assert!(tray_declaration.starts_with("\"{"));
        assert!(tray_declaration.contains(";\n\n#[derive"));
    }
}
