//! Fixed source and documentation for the native window-controls template.

use super::{TemplateContext, json_string, quoted, windows_path};

const TITLE_PROPOSAL: &str = "Window controls exercised";

pub(super) fn main_source(display_label: &str) -> String {
    let title = document(
        display_label,
        "This fixed walkthrough uses only typed, targetless session-window controls.",
        "template.controls.title",
        "Set host-composed title",
    );
    let resize = document(
        display_label,
        "The caption proposal was accepted. Request one bounded logical client size next.",
        "template.controls.resize",
        "Resize client area",
    );
    let maximize = document(
        display_label,
        "The host accepted the size request without returning geometry. Request maximise next.",
        "template.controls.maximize",
        "Maximise window",
    );
    let restore = document(
        display_label,
        "The host accepted the maximise request. Restore this same session window next.",
        "template.controls.restore",
        "Restore window",
    );
    let focus = document(
        display_label,
        "The host accepted the restore request. Ask Windows for foreground attention next.",
        "template.controls.focus",
        "Request foreground attention",
    );
    let fullscreen = document(
        display_label,
        "The host asked Windows for attention without reporting its result. Enter fullscreen next.",
        "template.controls.fullscreen",
        "Enter fullscreen",
    );
    let windowed = document(
        display_label,
        "The host accepted the borderless fullscreen request. Return to windowed presentation.",
        "template.controls.windowed",
        "Return to windowed",
    );
    let complete = document(
        display_label,
        "The host restored its retained framed presentation. Complete this session.",
        "template.controls.complete",
        "Complete window-controls session",
    );
    format!(
        "{MAIN_PREFIX}{};\nconst TITLE_DOCUMENT: &str = {};\nconst RESIZE_DOCUMENT: &str = {};\nconst MAXIMIZE_DOCUMENT: &str = {};\nconst RESTORE_DOCUMENT: &str = {};\nconst FOCUS_DOCUMENT: &str = {};\nconst FULLSCREEN_DOCUMENT: &str = {};\nconst WINDOWED_DOCUMENT: &str = {};\nconst COMPLETE_DOCUMENT: &str = {}{MAIN_SUFFIX}",
        quoted(TITLE_PROPOSAL),
        quoted(&title),
        quoted(&resize),
        quoted(&maximize),
        quoted(&restore),
        quoted(&focus),
        quoted(&fullscreen),
        quoted(&windowed),
        quoted(&complete),
    )
}

pub(super) fn readme(context: &TemplateContext) -> String {
    let host_manifest = windows_path(&context.host_manifest_path);
    format!(
        "# Native Anodrel window-controls template\n\nThis is a small Windows native project generated by anodrel-native-app-tool. It uses only first-party Anodrel crates, the Rust standard library, and the direct Windows invited-pipe adapter.\n\nThe program visibly walks through the existing targetless controls for its one host-owned session window: title proposal, logical client size, maximise, restore, foreground attention request, fullscreen, windowed restore, and self-close. It receives no native title, state, geometry, focus, monitor, handle, or delivery readback. It contains no raw protocol envelopes, host policy, capability declaration, configuration loader, network access, package identity, or signing behavior.\n\n## Build\n\nFrom this directory:\n\n~~~powershell\ncargo build --release\n~~~\n\nThis produces target\\release\\{project_slug}.exe. The project is intentionally not a product application, installer, or trusted executable.\n\n## Run in an Anodrel development session\n\nFrom this directory, pass the compiled executable to Anodrel's explicit window-controls development route:\n\n~~~powershell\n$clientPath = (Resolve-Path \".\\target\\release\\{project_slug}.exe\").Path\n$hostManifest = (Resolve-Path \"{host_manifest}\").Path\ncargo run --release --manifest-path $hostManifest -p anodrel-windows-host -- --native-window-controls-template-client $clientPath\n~~~\n\nThe host opens an Anodrel Native Window Controls Template window. Advance the actions in order: Set host-composed title, Resize client area, Maximise window, Restore window, Request foreground attention, Enter fullscreen, Return to windowed, and Complete window-controls session. The host grants exactly document replacement, semantic-action reading, the five existing targetless window controls, and self-close. It ignores every project-supplied capability, identity, title, window target, native handle, geometry, monitor, focus option, or host setting. Windows may decline foreground focus; the application receives only host acceptance, not a focus result.\n\nThe generated source expects its one-time private invitation only on standard input. Do not run the executable directly, pass it a pipe name, or put credentials in its arguments or environment.\n",
        project_slug = context.project_slug,
        host_manifest = host_manifest,
    )
}

fn document(display_label: &str, detail: &str, action: &str, action_label: &str) -> String {
    let label = json_string(display_label);
    let detail = json_string(detail);
    let action = json_string(action);
    let action_label = json_string(action_label);
    format!(
        "{{\"format\":\"anodrel.ui.document.v1\",\"root\":{{\"id\":\"template.controls.root\",\"kind\":\"stack\",\"axis\":\"vertical\",\"padding\":{{\"left\":56,\"top\":56,\"right\":56,\"bottom\":56}},\"gap\":16,\"surfaceTone\":\"plain\",\"children\":[{{\"id\":\"template.controls.eyebrow\",\"kind\":\"text\",\"value\":\"ANODREL WINDOW CONTROLS TEMPLATE\",\"fontSize\":14,\"tone\":\"accent\"}},{{\"id\":\"template.controls.display-name\",\"kind\":\"text\",\"value\":{label},\"fontSize\":28,\"tone\":\"primary\"}},{{\"id\":\"template.controls.detail\",\"kind\":\"text\",\"value\":{detail},\"fontSize\":16,\"tone\":\"secondary\"}},{{\"id\":{action},\"kind\":\"action\",\"label\":{action_label},\"fontSize\":16,\"enabled\":true,\"tone\":\"accent\"}}]}}}}"
    )
}

const MAIN_PREFIX: &str = r##"#![deny(unsafe_op_in_unsafe_fn)]

//! A constrained native Anodrel window-controls template.
//!
//! The host supplies one private bootstrap invitation on standard input. This
//! program opens only that invited Windows pipe, uses the five typed targetless
//! session-window controls, and never selects host capabilities or native
//! window resources.

use std::{process::ExitCode, thread};

use anodrel_windows_ui_sdk::{
    InteractivePollSchedule, WindowFullscreenMode, WindowSize, WindowState,
    WindowsUiConnectionError, WindowsUiSession,
};

const TITLE_ACTION: &str = "template.controls.title";
const RESIZE_ACTION: &str = "template.controls.resize";
const MAXIMIZE_ACTION: &str = "template.controls.maximize";
const RESTORE_ACTION: &str = "template.controls.restore";
const FOCUS_ACTION: &str = "template.controls.focus";
const FULLSCREEN_ACTION: &str = "template.controls.fullscreen";
const WINDOWED_ACTION: &str = "template.controls.windowed";
const COMPLETE_ACTION: &str = "template.controls.complete";
const TITLE_PROPOSAL: &str = "##;

const MAIN_SUFFIX: &str = r##";

#[derive(Clone, Copy)]
enum Stage {
    Completed,
    BootstrapUnreadable,
    EndpointUnavailable,
    AuthenticationRejected,
    DocumentRejected,
    EventReadFailed,
    ActionNotObserved,
    TitleRejected,
    StateRejected,
    FocusRejected,
    FullscreenRejected,
    SizeRejected,
    CloseRejected,
}

impl Stage {
    const fn code(self) -> u8 {
        match self {
            Self::Completed => 0,
            Self::BootstrapUnreadable => 101,
            Self::EndpointUnavailable => 102,
            Self::AuthenticationRejected => 103,
            Self::DocumentRejected => 104,
            Self::EventReadFailed => 105,
            Self::ActionNotObserved => 106,
            Self::TitleRejected => 107,
            Self::StateRejected => 108,
            Self::FocusRejected => 109,
            Self::FullscreenRejected => 110,
            Self::SizeRejected => 111,
            Self::CloseRejected => 112,
        }
    }
}

fn main() -> ExitCode {
    ExitCode::from(run().code())
}

fn run() -> Stage {
    let mut session = match WindowsUiSession::connect_from_stdin() {
        Ok(session) => session,
        Err(WindowsUiConnectionError::BootstrapUnavailable) => return Stage::BootstrapUnreadable,
        Err(WindowsUiConnectionError::InvitedEndpointUnavailable) => {
            return Stage::EndpointUnavailable;
        }
        Err(WindowsUiConnectionError::AuthenticationUnavailable) => {
            return Stage::AuthenticationRejected;
        }
    };

    let revision = match publish(&mut session, TITLE_DOCUMENT, 1) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, TITLE_ACTION, revision) {
        return stage;
    }
    if session.set_window_title(TITLE_PROPOSAL).is_err() {
        return Stage::TitleRejected;
    }

    let revision = match publish(&mut session, RESIZE_DOCUMENT, 2) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, RESIZE_ACTION, revision) {
        return stage;
    }
    let size = WindowSize::new(960, 640).expect("fixed window-controls size is valid");
    if session.set_window_size(size).is_err() {
        return Stage::SizeRejected;
    }

    let revision = match publish(&mut session, MAXIMIZE_DOCUMENT, 3) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, MAXIMIZE_ACTION, revision) {
        return stage;
    }
    if session.set_window_state(WindowState::Maximized).is_err() {
        return Stage::StateRejected;
    }

    let revision = match publish(&mut session, RESTORE_DOCUMENT, 4) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, RESTORE_ACTION, revision) {
        return stage;
    }
    if session.set_window_state(WindowState::Restored).is_err() {
        return Stage::StateRejected;
    }

    let revision = match publish(&mut session, FOCUS_DOCUMENT, 5) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, FOCUS_ACTION, revision) {
        return stage;
    }
    if session.request_window_focus().is_err() {
        return Stage::FocusRejected;
    }

    let revision = match publish(&mut session, FULLSCREEN_DOCUMENT, 6) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, FULLSCREEN_ACTION, revision) {
        return stage;
    }
    if session
        .set_window_fullscreen(WindowFullscreenMode::Fullscreen)
        .is_err()
    {
        return Stage::FullscreenRejected;
    }

    let revision = match publish(&mut session, WINDOWED_DOCUMENT, 7) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, WINDOWED_ACTION, revision) {
        return stage;
    }
    if session
        .set_window_fullscreen(WindowFullscreenMode::Windowed)
        .is_err()
    {
        return Stage::FullscreenRejected;
    }

    let revision = match publish(&mut session, COMPLETE_DOCUMENT, 8) {
        Ok(revision) => revision,
        Err(stage) => return stage,
    };
    if let Err(stage) = wait_for_action(&mut session, COMPLETE_ACTION, revision) {
        return stage;
    }
    if session.close().is_err() {
        return Stage::CloseRejected;
    }
    Stage::Completed
}

fn publish(
    session: &mut WindowsUiSession,
    document: &str,
    expected_revision: u64,
) -> Result<u64, Stage> {
    let revision = session
        .replace_document_v1(document)
        .map_err(|_| Stage::DocumentRejected)?;
    if revision.value() == expected_revision {
        Ok(revision.value())
    } else {
        Err(Stage::DocumentRejected)
    }
}

fn wait_for_action(
    session: &mut WindowsUiSession,
    expected_action: &str,
    expected_revision: u64,
) -> Result<(), Stage> {
    for interval in InteractivePollSchedule::new() {
        let batch = session.read_actions().map_err(|_| Stage::EventReadFailed)?;
        if batch.dropped() != 0 || batch.discarded() != 0 {
            return Err(Stage::EventReadFailed);
        }
        match batch.actions() {
            [] => thread::sleep(interval),
            [action]
                if action.action() == expected_action
                    && action.revision().value() == expected_revision => return Ok(()),
            _ => return Err(Stage::EventReadFailed),
        }
    }
    Err(Stage::ActionNotObserved)
}
"##;

#[cfg(test)]
mod tests {
    use super::{TITLE_PROPOSAL, document};

    #[test]
    fn every_fixed_walkthrough_document_uses_the_strict_v1_contract() {
        for (action, label) in [
            ("template.controls.title", "Set title"),
            ("template.controls.resize", "Resize"),
            ("template.controls.maximize", "Maximize"),
            ("template.controls.restore", "Restore"),
            ("template.controls.focus", "Focus"),
            ("template.controls.fullscreen", "Fullscreen"),
            ("template.controls.windowed", "Windowed"),
            ("template.controls.complete", "Complete"),
        ] {
            let document = document(
                "Generated Window Controls Template",
                "Detail",
                action,
                label,
            );
            let decoded = anodrel_ui_document::decode(&document)
                .unwrap_or_else(|error| panic!("{action} generated document is invalid: {error}"));
            assert_eq!(decoded.root().id().as_str(), "template.controls.root");
        }
        assert_eq!(TITLE_PROPOSAL, "Window controls exercised");
    }
}
