[package]
name = "anodrel-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-clipboard = { path = "../clipboard" }
anodrel-external-links = { path = "../external-links" }
anodrel-protocol = { path = "../protocol" }
anodrel-ui-session = { path = "../ui-session" }

[dev-dependencies]
anodrel-ui = { path = "../ui" }
