[package]
name = "anodrel-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-clipboard = { path = "../clipboard" }
anodrel-credentials = { path = "../credentials" }
anodrel-diagnostics = { path = "../diagnostics" }
anodrel-external-links = { path = "../external-links" }
anodrel-file-access = { path = "../file-access" }
anodrel-file-dialog = { path = "../file-dialog" }
anodrel-notifications = { path = "../notifications" }
anodrel-storage = { path = "../storage" }
anodrel-protocol = { path = "../protocol" }
anodrel-ui-session = { path = "../ui-session" }

[dev-dependencies]
anodrel-ui = { path = "../ui" }
