[package]
name = "anodrel-ui-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-client = { path = "../client" }
anodrel-json = { path = "../json" }
anodrel-menu = { path = "../menu" }
anodrel-notifications = { path = "../notifications" }
anodrel-ui = { path = "../ui" }
anodrel-ui-document = { path = "../ui-document" }
anodrel-ui-session = { path = "../ui-session" }
anodrel-window = { path = "../window" }

[dev-dependencies]
anodrel-bootstrap = { path = "../bootstrap" }
anodrel-wire = { path = "../wire" }
