[package]
name = "anodrel-windows-update-catalogue-signature"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-update-catalogue = { path = "../../crates/update-catalogue" }
anodrel-windows-signing = { path = "../windows-signing" }
anodrel-windows-installer = { path = "../../tools/windows-installer" }
