[package]
name = "anodrel-windows-installer"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "anodrel-windows-installer"
path = "src/main.rs"

[dependencies]
anodrel-application = { path = "../../crates/application" }
anodrel-json = { path = "../../crates/json" }
anodrel-network = { path = "../../crates/network" }
anodrel-protocol = { path = "../../crates/protocol" }
anodrel-release-bundle = { path = "../../crates/release-bundle" }
anodrel-windows-signature = { path = "../../adapters/windows-signature" }
