[package]
name = "anodrel-windows-pipe"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-bootstrap = { path = "../../crates/bootstrap" }
anodrel-clipboard = { path = "../../crates/clipboard" }
anodrel-core = { path = "../../crates/core" }
anodrel-external-links = { path = "../../crates/external-links" }
anodrel-file-access = { path = "../../crates/file-access" }
anodrel-file-dialog = { path = "../../crates/file-dialog" }
anodrel-protocol = { path = "../../crates/protocol" }
anodrel-transport = { path = "../../crates/transport" }
anodrel-wire = { path = "../../crates/wire" }
