[package]
name = "anodrel-windows-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anodrel-application = { path = "../../crates/application" }
anodrel-core = { path = "../../crates/core" }
anodrel-session-policy = { path = "../../crates/session-policy" }
